import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader, LoadingState } from "@/components/admin-ui";
import { listCompanySubscriptions, listPlans, saveCompanySubscription, updateSubscriptionStatus } from "@/lib/subscriptions";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/_authenticated/admin/subscriptions")({ component: SubscriptionsPage });
function SubscriptionsPage() {
  const qc = useQueryClient(); const subscriptions = useQuery({ queryKey: ["admin", "subscriptions"], queryFn: listCompanySubscriptions }); const plans = useQuery({ queryKey: ["subscriptions", "plans"], queryFn: () => listPlans(false) }); const companies = useQuery({ queryKey: ["admin", "subscription-companies"], queryFn: async () => { const { data, error } = await supabase.from("companies").select("id, name").is("deleted_at", null).order("name"); if (error) throw error; return data ?? []; } }); const [companyId, setCompanyId] = useState(""); const [planId, setPlanId] = useState(""); const [expiresAt, setExpiresAt] = useState("");
  const assign = async (event: React.FormEvent) => { event.preventDefault(); try { await saveCompanySubscription({ company_id: companyId, plan_id: planId, expires_at: expiresAt || null }); toast.success("Assinatura atribuída."); setCompanyId(""); setPlanId(""); setExpiresAt(""); await qc.invalidateQueries({ queryKey: ["admin", "subscriptions"] }); } catch { toast.error("Não foi possível atribuir a assinatura."); } };
  const changeStatus = async (id: string, status: string) => { try { await updateSubscriptionStatus(id, status); await qc.invalidateQueries({ queryKey: ["admin", "subscriptions"] }); toast.success("Status atualizado."); } catch { toast.error("Não foi possível atualizar o status."); } };
  return <div><PageHeader title="Assinaturas" description="Atribua e administre os planos das empresas." /><Card className="mb-6"><CardHeader><CardTitle>Atribuir plano</CardTitle></CardHeader><CardContent><form onSubmit={assign} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="space-y-1.5"><Label>Empresa</Label><Select value={companyId} onValueChange={setCompanyId}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{(companies.data ?? []).map((company) => <SelectItem key={company.id} value={company.id}>{company.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Plano</Label><Select value={planId} onValueChange={setPlanId}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{(plans.data ?? []).map((plan) => <SelectItem key={plan.id} value={plan.id}>{plan.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Vencimento</Label><Input type="date" value={expiresAt} onChange={(e) => setExpiresAt(e.target.value)} /></div><div className="flex items-end"><Button type="submit" disabled={!companyId || !planId}>Atribuir assinatura</Button></div></form></CardContent></Card>{subscriptions.isLoading ? <LoadingState /> : <div className="space-y-3">{(subscriptions.data ?? []).map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{item.company?.name ?? item.company_id}</p><p className="text-sm text-muted-foreground">{item.plan?.name ?? "Plano removido"} · {item.expires_at ? `vence em ${new Date(item.expires_at).toLocaleDateString("pt-BR")}` : "sem vencimento"}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-muted px-3 py-1 text-sm">{item.status}</span>{item.status !== "active" && <Button size="sm" variant="outline" onClick={() => changeStatus(item.id, "active")}>Reativar</Button>}{item.status === "active" && <><Button size="sm" variant="outline" onClick={() => changeStatus(item.id, "suspended")}>Suspender</Button><Button size="sm" variant="outline" onClick={() => changeStatus(item.id, "cancelled")}>Cancelar</Button></>}</div></CardContent></Card>)}</div>}</div>;
}
