import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Pencil, Plus } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader, StatusBadge, LoadingState } from "@/components/admin-ui";
import { listPlans, plansKey, savePlan, setPlanStatus, type SubscriptionPlan } from "@/lib/subscriptions";

export const Route = createFileRoute("/_authenticated/admin/plans")({ component: PlansPage });
const empty = { code: "", name: "", description: "", price_monthly: "0", duration_days: "30", invitations_limit: "", customers_limit: "", guests_limit: "", storage_limit_mb: "" };
function PlansPage() {
  const qc = useQueryClient(); const query = useQuery({ queryKey: plansKey, queryFn: () => listPlans() }); const [editing, setEditing] = useState<SubscriptionPlan | null>(null); const [form, setForm] = useState(empty); const [open, setOpen] = useState(false);
  const start = (plan?: SubscriptionPlan) => { setEditing(plan ?? null); setForm(plan ? { code: plan.code, name: plan.name, description: plan.description ?? "", price_monthly: String(plan.price_monthly), duration_days: String(plan.duration_days), invitations_limit: plan.invitations_limit == null ? "" : String(plan.invitations_limit), customers_limit: plan.customers_limit == null ? "" : String(plan.customers_limit), guests_limit: plan.guests_limit == null ? "" : String(plan.guests_limit), storage_limit_mb: plan.storage_limit_mb == null ? "" : String(plan.storage_limit_mb) } : empty); setOpen(true); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await savePlan({ ...form, price_monthly: Number(form.price_monthly), duration_days: Number(form.duration_days), invitations_limit: form.invitations_limit ? Number(form.invitations_limit) : null, customers_limit: form.customers_limit ? Number(form.customers_limit) : null, guests_limit: form.guests_limit ? Number(form.guests_limit) : null, storage_limit_mb: form.storage_limit_mb ? Number(form.storage_limit_mb) : null }, editing?.id); toast.success("Plano salvo."); setOpen(false); await qc.invalidateQueries({ queryKey: plansKey }); } catch { toast.error("Não foi possível salvar o plano."); } };
  return <div><PageHeader title="Planos" description="Configure limites e preços disponíveis para as empresas." action={<Button onClick={() => start()}><Plus className="h-4 w-4" />Novo plano</Button>} />{open && <Card className="mb-6"><CardHeader><CardTitle>{editing ? "Editar plano" : "Novo plano"}</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{([["code","Código"],["name","Nome"],["price_monthly","Preço mensal"],["duration_days","Duração em dias"],["invitations_limit","Limite de convites"],["customers_limit","Limite de clientes"],["guests_limit","Limite de convidados"],["storage_limit_mb","Armazenamento (MB)"]] as [string, string][]).map(([key,label]) => <div key={key} className="space-y-1.5"><Label htmlFor={key}>{label}</Label><Input id={key} type={key === "price_monthly" || key.includes("limit") || key === "duration_days" ? "number" : "text"} value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} required={key === "code" || key === "name"} /></div>)}<div className="space-y-1.5 sm:col-span-2 lg:col-span-3"><Label htmlFor="description">Descrição</Label><Textarea id="description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="flex gap-2 sm:col-span-2 lg:col-span-3"><Button type="submit">Salvar</Button><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancelar</Button></div></form></CardContent></Card>}{query.isLoading ? <LoadingState /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(query.data ?? []).map((plan) => <Card key={plan.id}><CardHeader className="flex flex-row items-start justify-between gap-3"><div><CardTitle>{plan.name}</CardTitle><p className="text-sm text-muted-foreground">{plan.code}</p></div><StatusBadge status={plan.status} /></CardHeader><CardContent className="space-y-3 text-sm"><p>{plan.description || "Sem descrição."}</p><p className="text-lg font-semibold">{plan.price_monthly.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}<span className="text-xs font-normal text-muted-foreground"> / mês</span></p><div className="grid grid-cols-2 gap-2 text-muted-foreground"><span>Convites: {plan.invitations_limit ?? "Ilimitado"}</span><span>Clientes: {plan.customers_limit ?? "Ilimitado"}</span><span>Convidados: {plan.guests_limit ?? "Ilimitado"}</span><span>Armazenamento: {plan.storage_limit_mb ?? "Ilimitado"} MB</span></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => start(plan)}><Pencil className="h-4 w-4" />Editar</Button><Button size="sm" variant="outline" onClick={async () => { await setPlanStatus(plan.id, plan.status === "active" ? "inactive" : "active"); await qc.invalidateQueries({ queryKey: plansKey }); }}>{plan.status === "active" ? "Desativar" : "Ativar"}</Button></div></CardContent></Card>)}</div>}</div>;
}
