/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as FirstAccessRouteImport } from './routes/first-access'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtecaoDadosRouteImport } from './routes/protecao-dados'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as ConviteSlugRouteImport } from './routes/convite.$slug'
import { Route as PainelConviteTokenRouteImport } from './routes/painel-convite.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSectionRouteImport } from './routes/_authenticated/admin.$section'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminTrashRouteImport } from './routes/_authenticated/admin.trash'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardSectionRouteImport } from './routes/_authenticated/dashboard.$section'
import { Route as AuthenticatedDashboardAssinaturaRouteImport } from './routes/_authenticated/dashboard.assinatura'
import { Route as AuthenticatedInvitationsIndexRouteImport } from './routes/_authenticated/invitations.index'
import { Route as AuthenticatedInvitationsNewRouteImport } from './routes/_authenticated/invitations.new'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedSettingsBrandRouteImport } from './routes/_authenticated/settings.brand'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates.index'
import { Route as AuthenticatedTemplatesIdRouteImport } from './routes/_authenticated/templates.$id'
import { Route as AuthenticatedTemplatesNewRouteImport } from './routes/_authenticated/templates.new'
import { Route as AuthenticatedAdminCompaniesIndexRouteImport } from './routes/_authenticated/admin.companies.index'
import { Route as AuthenticatedAdminCompaniesIdRouteImport } from './routes/_authenticated/admin.companies.$id'
import { Route as AuthenticatedAdminCompaniesNewRouteImport } from './routes/_authenticated/admin.companies.new'
import { Route as AuthenticatedAdminTemplatesIndexRouteImport } from './routes/_authenticated/admin.templates.index'
import { Route as AuthenticatedAdminTemplatesIdRouteImport } from './routes/_authenticated/admin.templates.$id'
import { Route as AuthenticatedAdminTemplatesNewRouteImport } from './routes/_authenticated/admin.templates.new'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin.users.index'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'
import { Route as AuthenticatedAdminUsersNewRouteImport } from './routes/_authenticated/admin.users.new'
import { Route as AuthenticatedInvitationsIdCheckinRouteImport } from './routes/_authenticated/invitations.$id.checkin'
import { Route as AuthenticatedInvitationsIdEditorRouteImport } from './routes/_authenticated/invitations.$id.editor'
import { Route as AuthenticatedInvitationsIdGuestsRouteImport } from './routes/_authenticated/invitations.$id.guests'
import { Route as AuthenticatedInvitationsIdPreviewRouteImport } from './routes/_authenticated/invitations.$id.preview'
import { Route as AuthenticatedInvitationsIdReportRouteImport } from './routes/_authenticated/invitations.$id.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAccessRoute = FirstAccessRouteImport.update({
  id: '/first-access',
  path: '/first-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtecaoDadosRoute = ProtecaoDadosRouteImport.update({
  id: '/protecao-dados',
  path: '/protecao-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConviteSlugRoute = ConviteSlugRouteImport.update({
  id: '/convite/$slug',
  path: '/convite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelConviteTokenRoute = PainelConviteTokenRouteImport.update({
  id: '/painel-convite/$token',
  path: '/painel-convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSectionRoute =
  AuthenticatedAdminSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrashRoute = AuthenticatedAdminTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSectionRoute =
  AuthenticatedDashboardSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAssinaturaRoute =
  AuthenticatedDashboardAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedInvitationsIndexRoute =
  AuthenticatedInvitationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvitationsRoute,
  } as any)
const AuthenticatedInvitationsNewRoute =
  AuthenticatedInvitationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInvitationsRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedSettingsBrandRoute =
  AuthenticatedSettingsBrandRouteImport.update({
    id: '/brand',
    path: '/brand',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTemplatesRoute,
  } as any)
const AuthenticatedTemplatesIdRoute =
  AuthenticatedTemplatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTemplatesRoute,
  } as any)
const AuthenticatedTemplatesNewRoute =
  AuthenticatedTemplatesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTemplatesRoute,
  } as any)
const AuthenticatedAdminCompaniesIndexRoute =
  AuthenticatedAdminCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesIdRoute =
  AuthenticatedAdminCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesNewRoute =
  AuthenticatedAdminCompaniesNewRouteImport.update({
    id: '/companies/new',
    path: '/companies/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesIndexRoute =
  AuthenticatedAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesIdRoute =
  AuthenticatedAdminTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesNewRoute =
  AuthenticatedAdminTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersNewRoute =
  AuthenticatedAdminUsersNewRouteImport.update({
    id: '/users/new',
    path: '/users/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedInvitationsIdCheckinRoute =
  AuthenticatedInvitationsIdCheckinRouteImport.update({
    id: '/$id/checkin',
    path: '/$id/checkin',
    getParentRoute: () => AuthenticatedInvitationsRoute,
  } as any)
const AuthenticatedInvitationsIdEditorRoute =
  AuthenticatedInvitationsIdEditorRouteImport.update({
    id: '/$id/editor',
    path: '/$id/editor',
    getParentRoute: () => AuthenticatedInvitationsRoute,
  } as any)
const AuthenticatedInvitationsIdGuestsRoute =
  AuthenticatedInvitationsIdGuestsRouteImport.update({
    id: '/$id/guests',
    path: '/$id/guests',
    getParentRoute: () => AuthenticatedInvitationsRoute,
  } as any)
const AuthenticatedInvitationsIdPreviewRoute =
  AuthenticatedInvitationsIdPreviewRouteImport.update({
    id: '/$id/preview',
    path: '/$id/preview',
    getParentRoute: () => AuthenticatedInvitationsRoute,
  } as any)
const AuthenticatedInvitationsIdReportRoute =
  AuthenticatedInvitationsIdReportRouteImport.update({
    id: '/$id/report',
    path: '/$id/report',
    getParentRoute: () => AuthenticatedInvitationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/first-access': typeof FirstAccessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/protecao-dados': typeof ProtecaoDadosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/invitations': typeof AuthenticatedInvitationsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/convite/$slug': typeof ConviteSlugRoute
  '/painel-convite/$token': typeof PainelConviteTokenRoute
  '/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/trash': typeof AuthenticatedAdminTrashRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/dashboard/assinatura': typeof AuthenticatedDashboardAssinaturaRoute
  '/invitations/new': typeof AuthenticatedInvitationsNewRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/invitations/': typeof AuthenticatedInvitationsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/companies/new': typeof AuthenticatedAdminCompaniesNewRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdRoute
  '/admin/templates/new': typeof AuthenticatedAdminTemplatesNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/invitations/$id/checkin': typeof AuthenticatedInvitationsIdCheckinRoute
  '/invitations/$id/editor': typeof AuthenticatedInvitationsIdEditorRoute
  '/invitations/$id/guests': typeof AuthenticatedInvitationsIdGuestsRoute
  '/invitations/$id/preview': typeof AuthenticatedInvitationsIdPreviewRoute
  '/invitations/$id/report': typeof AuthenticatedInvitationsIdReportRoute
  '/admin/companies/': typeof AuthenticatedAdminCompaniesIndexRoute
  '/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/first-access': typeof FirstAccessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/protecao-dados': typeof ProtecaoDadosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/convite/$slug': typeof ConviteSlugRoute
  '/painel-convite/$token': typeof PainelConviteTokenRoute
  '/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/trash': typeof AuthenticatedAdminTrashRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/dashboard/assinatura': typeof AuthenticatedDashboardAssinaturaRoute
  '/invitations/new': typeof AuthenticatedInvitationsNewRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/invitations': typeof AuthenticatedInvitationsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/companies/new': typeof AuthenticatedAdminCompaniesNewRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdRoute
  '/admin/templates/new': typeof AuthenticatedAdminTemplatesNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/invitations/$id/checkin': typeof AuthenticatedInvitationsIdCheckinRoute
  '/invitations/$id/editor': typeof AuthenticatedInvitationsIdEditorRoute
  '/invitations/$id/guests': typeof AuthenticatedInvitationsIdGuestsRoute
  '/invitations/$id/preview': typeof AuthenticatedInvitationsIdPreviewRoute
  '/invitations/$id/report': typeof AuthenticatedInvitationsIdReportRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesIndexRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/first-access': typeof FirstAccessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/protecao-dados': typeof ProtecaoDadosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/convite/$slug': typeof ConviteSlugRoute
  '/painel-convite/$token': typeof PainelConviteTokenRoute
  '/_authenticated/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/trash': typeof AuthenticatedAdminTrashRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/_authenticated/dashboard/assinatura': typeof AuthenticatedDashboardAssinaturaRoute
  '/_authenticated/invitations/new': typeof AuthenticatedInvitationsNewRoute
  '/_authenticated/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/_authenticated/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/_authenticated/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/invitations/': typeof AuthenticatedInvitationsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/_authenticated/admin/companies/new': typeof AuthenticatedAdminCompaniesNewRoute
  '/_authenticated/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdRoute
  '/_authenticated/admin/templates/new': typeof AuthenticatedAdminTemplatesNewRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/_authenticated/invitations/$id/checkin': typeof AuthenticatedInvitationsIdCheckinRoute
  '/_authenticated/invitations/$id/editor': typeof AuthenticatedInvitationsIdEditorRoute
  '/_authenticated/invitations/$id/guests': typeof AuthenticatedInvitationsIdGuestsRoute
  '/_authenticated/invitations/$id/preview': typeof AuthenticatedInvitationsIdPreviewRoute
  '/_authenticated/invitations/$id/report': typeof AuthenticatedInvitationsIdReportRoute
  '/_authenticated/admin/companies/': typeof AuthenticatedAdminCompaniesIndexRoute
  '/_authenticated/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/first-access'
    | '/forgot-password'
    | '/login'
    | '/protecao-dados'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/invitations'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/convite/$slug'
    | '/painel-convite/$token'
    | '/admin/$section'
    | '/admin/plans'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/trash'
    | '/customers/$id'
    | '/dashboard/$section'
    | '/dashboard/assinatura'
    | '/invitations/new'
    | '/settings/brand'
    | '/templates/$id'
    | '/templates/new'
    | '/admin/'
    | '/customers/'
    | '/dashboard/'
    | '/invitations/'
    | '/reports/'
    | '/templates/'
    | '/admin/companies/$id'
    | '/admin/companies/new'
    | '/admin/templates/$id'
    | '/admin/templates/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/invitations/$id/checkin'
    | '/invitations/$id/editor'
    | '/invitations/$id/guests'
    | '/invitations/$id/preview'
    | '/invitations/$id/report'
    | '/admin/companies/'
    | '/admin/templates/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/first-access'
    | '/forgot-password'
    | '/login'
    | '/protecao-dados'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/settings'
    | '/convite/$slug'
    | '/painel-convite/$token'
    | '/admin/$section'
    | '/admin/plans'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/trash'
    | '/customers/$id'
    | '/dashboard/$section'
    | '/dashboard/assinatura'
    | '/invitations/new'
    | '/settings/brand'
    | '/templates/$id'
    | '/templates/new'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/invitations'
    | '/reports'
    | '/templates'
    | '/admin/companies/$id'
    | '/admin/companies/new'
    | '/admin/templates/$id'
    | '/admin/templates/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/invitations/$id/checkin'
    | '/invitations/$id/editor'
    | '/invitations/$id/guests'
    | '/invitations/$id/preview'
    | '/invitations/$id/report'
    | '/admin/companies'
    | '/admin/templates'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/first-access'
    | '/forgot-password'
    | '/login'
    | '/protecao-dados'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/invitations'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/convite/$slug'
    | '/painel-convite/$token'
    | '/_authenticated/admin/$section'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/trash'
    | '/_authenticated/customers/$id'
    | '/_authenticated/dashboard/$section'
    | '/_authenticated/dashboard/assinatura'
    | '/_authenticated/invitations/new'
    | '/_authenticated/settings/brand'
    | '/_authenticated/templates/$id'
    | '/_authenticated/templates/new'
    | '/_authenticated/admin/'
    | '/_authenticated/customers/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/invitations/'
    | '/_authenticated/reports/'
    | '/_authenticated/templates/'
    | '/_authenticated/admin/companies/$id'
    | '/_authenticated/admin/companies/new'
    | '/_authenticated/admin/templates/$id'
    | '/_authenticated/admin/templates/new'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/admin/users/new'
    | '/_authenticated/invitations/$id/checkin'
    | '/_authenticated/invitations/$id/editor'
    | '/_authenticated/invitations/$id/guests'
    | '/_authenticated/invitations/$id/preview'
    | '/_authenticated/invitations/$id/report'
    | '/_authenticated/admin/companies/'
    | '/_authenticated/admin/templates/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  FirstAccessRoute: typeof FirstAccessRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProtecaoDadosRoute: typeof ProtecaoDadosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  ConviteSlugRoute: typeof ConviteSlugRoute
  PainelConviteTokenRoute: typeof PainelConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-access': {
      id: '/first-access'
      path: '/first-access'
      fullPath: '/first-access'
      preLoaderRoute: typeof FirstAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protecao-dados': {
      id: '/protecao-dados'
      path: '/protecao-dados'
      fullPath: '/protecao-dados'
      preLoaderRoute: typeof ProtecaoDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/convite/$slug': {
      id: '/convite/$slug'
      path: '/convite/$slug'
      fullPath: '/convite/$slug'
      preLoaderRoute: typeof ConviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-convite/$token': {
      id: '/painel-convite/$token'
      path: '/painel-convite/$token'
      fullPath: '/painel-convite/$token'
      preLoaderRoute: typeof PainelConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$section': {
      id: '/_authenticated/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AuthenticatedAdminSectionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trash': {
      id: '/_authenticated/admin/trash'
      path: '/trash'
      fullPath: '/admin/trash'
      preLoaderRoute: typeof AuthenticatedAdminTrashRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/$section': {
      id: '/_authenticated/dashboard/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof AuthenticatedDashboardSectionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assinatura': {
      id: '/_authenticated/dashboard/assinatura'
      path: '/assinatura'
      fullPath: '/dashboard/assinatura'
      preLoaderRoute: typeof AuthenticatedDashboardAssinaturaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/invitations/': {
      id: '/_authenticated/invitations/'
      path: '/'
      fullPath: '/invitations/'
      preLoaderRoute: typeof AuthenticatedInvitationsIndexRouteImport
      parentRoute: typeof AuthenticatedInvitationsRoute
    }
    '/_authenticated/invitations/new': {
      id: '/_authenticated/invitations/new'
      path: '/new'
      fullPath: '/invitations/new'
      preLoaderRoute: typeof AuthenticatedInvitationsNewRouteImport
      parentRoute: typeof AuthenticatedInvitationsRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/settings/brand': {
      id: '/_authenticated/settings/brand'
      path: '/brand'
      fullPath: '/settings/brand'
      preLoaderRoute: typeof AuthenticatedSettingsBrandRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedTemplatesRoute
    }
    '/_authenticated/templates/$id': {
      id: '/_authenticated/templates/$id'
      path: '/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AuthenticatedTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedTemplatesRoute
    }
    '/_authenticated/templates/new': {
      id: '/_authenticated/templates/new'
      path: '/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthenticatedTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedTemplatesRoute
    }
    '/_authenticated/admin/companies/': {
      id: '/_authenticated/admin/companies/'
      path: '/companies'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies/$id': {
      id: '/_authenticated/admin/companies/$id'
      path: '/companies/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies/new': {
      id: '/_authenticated/admin/companies/new'
      path: '/companies/new'
      fullPath: '/admin/companies/new'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates/': {
      id: '/_authenticated/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates/$id': {
      id: '/_authenticated/admin/templates/$id'
      path: '/templates/$id'
      fullPath: '/admin/templates/$id'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates/new': {
      id: '/_authenticated/admin/templates/new'
      path: '/templates/new'
      fullPath: '/admin/templates/new'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/new': {
      id: '/_authenticated/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AuthenticatedAdminUsersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/invitations/$id/checkin': {
      id: '/_authenticated/invitations/$id/checkin'
      path: '/$id/checkin'
      fullPath: '/invitations/$id/checkin'
      preLoaderRoute: typeof AuthenticatedInvitationsIdCheckinRouteImport
      parentRoute: typeof AuthenticatedInvitationsRoute
    }
    '/_authenticated/invitations/$id/editor': {
      id: '/_authenticated/invitations/$id/editor'
      path: '/$id/editor'
      fullPath: '/invitations/$id/editor'
      preLoaderRoute: typeof AuthenticatedInvitationsIdEditorRouteImport
      parentRoute: typeof AuthenticatedInvitationsRoute
    }
    '/_authenticated/invitations/$id/guests': {
      id: '/_authenticated/invitations/$id/guests'
      path: '/$id/guests'
      fullPath: '/invitations/$id/guests'
      preLoaderRoute: typeof AuthenticatedInvitationsIdGuestsRouteImport
      parentRoute: typeof AuthenticatedInvitationsRoute
    }
    '/_authenticated/invitations/$id/preview': {
      id: '/_authenticated/invitations/$id/preview'
      path: '/$id/preview'
      fullPath: '/invitations/$id/preview'
      preLoaderRoute: typeof AuthenticatedInvitationsIdPreviewRouteImport
      parentRoute: typeof AuthenticatedInvitationsRoute
    }
    '/_authenticated/invitations/$id/report': {
      id: '/_authenticated/invitations/$id/report'
      path: '/$id/report'
      fullPath: '/invitations/$id/report'
      preLoaderRoute: typeof AuthenticatedInvitationsIdReportRouteImport
      parentRoute: typeof AuthenticatedInvitationsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSectionRoute: typeof AuthenticatedAdminSectionRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminTrashRoute: typeof AuthenticatedAdminTrashRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCompaniesIdRoute: typeof AuthenticatedAdminCompaniesIdRoute
  AuthenticatedAdminCompaniesNewRoute: typeof AuthenticatedAdminCompaniesNewRoute
  AuthenticatedAdminTemplatesIdRoute: typeof AuthenticatedAdminTemplatesIdRoute
  AuthenticatedAdminTemplatesNewRoute: typeof AuthenticatedAdminTemplatesNewRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminUsersNewRoute: typeof AuthenticatedAdminUsersNewRoute
  AuthenticatedAdminCompaniesIndexRoute: typeof AuthenticatedAdminCompaniesIndexRoute
  AuthenticatedAdminTemplatesIndexRoute: typeof AuthenticatedAdminTemplatesIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSectionRoute: AuthenticatedAdminSectionRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminTrashRoute: AuthenticatedAdminTrashRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCompaniesIdRoute: AuthenticatedAdminCompaniesIdRoute,
  AuthenticatedAdminCompaniesNewRoute: AuthenticatedAdminCompaniesNewRoute,
  AuthenticatedAdminTemplatesIdRoute: AuthenticatedAdminTemplatesIdRoute,
  AuthenticatedAdminTemplatesNewRoute: AuthenticatedAdminTemplatesNewRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  AuthenticatedAdminUsersNewRoute: AuthenticatedAdminUsersNewRoute,
  AuthenticatedAdminCompaniesIndexRoute: AuthenticatedAdminCompaniesIndexRoute,
  AuthenticatedAdminTemplatesIndexRoute: AuthenticatedAdminTemplatesIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
    AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardSectionRoute: typeof AuthenticatedDashboardSectionRoute
  AuthenticatedDashboardAssinaturaRoute: typeof AuthenticatedDashboardAssinaturaRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardSectionRoute: AuthenticatedDashboardSectionRoute,
    AuthenticatedDashboardAssinaturaRoute:
      AuthenticatedDashboardAssinaturaRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedInvitationsRouteChildren {
  AuthenticatedInvitationsNewRoute: typeof AuthenticatedInvitationsNewRoute
  AuthenticatedInvitationsIndexRoute: typeof AuthenticatedInvitationsIndexRoute
  AuthenticatedInvitationsIdCheckinRoute: typeof AuthenticatedInvitationsIdCheckinRoute
  AuthenticatedInvitationsIdEditorRoute: typeof AuthenticatedInvitationsIdEditorRoute
  AuthenticatedInvitationsIdGuestsRoute: typeof AuthenticatedInvitationsIdGuestsRoute
  AuthenticatedInvitationsIdPreviewRoute: typeof AuthenticatedInvitationsIdPreviewRoute
  AuthenticatedInvitationsIdReportRoute: typeof AuthenticatedInvitationsIdReportRoute
}

const AuthenticatedInvitationsRouteChildren: AuthenticatedInvitationsRouteChildren =
  {
    AuthenticatedInvitationsNewRoute: AuthenticatedInvitationsNewRoute,
    AuthenticatedInvitationsIndexRoute: AuthenticatedInvitationsIndexRoute,
    AuthenticatedInvitationsIdCheckinRoute:
      AuthenticatedInvitationsIdCheckinRoute,
    AuthenticatedInvitationsIdEditorRoute:
      AuthenticatedInvitationsIdEditorRoute,
    AuthenticatedInvitationsIdGuestsRoute:
      AuthenticatedInvitationsIdGuestsRoute,
    AuthenticatedInvitationsIdPreviewRoute:
      AuthenticatedInvitationsIdPreviewRoute,
    AuthenticatedInvitationsIdReportRoute:
      AuthenticatedInvitationsIdReportRoute,
  }

const AuthenticatedInvitationsRouteWithChildren =
  AuthenticatedInvitationsRoute._addFileChildren(
    AuthenticatedInvitationsRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBrandRoute: typeof AuthenticatedSettingsBrandRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBrandRoute: AuthenticatedSettingsBrandRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedTemplatesRouteChildren {
  AuthenticatedTemplatesIdRoute: typeof AuthenticatedTemplatesIdRoute
  AuthenticatedTemplatesNewRoute: typeof AuthenticatedTemplatesNewRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedTemplatesRouteChildren: AuthenticatedTemplatesRouteChildren =
  {
    AuthenticatedTemplatesIdRoute: AuthenticatedTemplatesIdRoute,
    AuthenticatedTemplatesNewRoute: AuthenticatedTemplatesNewRoute,
    AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  }

const AuthenticatedTemplatesRouteWithChildren =
  AuthenticatedTemplatesRoute._addFileChildren(
    AuthenticatedTemplatesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  FirstAccessRoute: FirstAccessRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProtecaoDadosRoute: ProtecaoDadosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  ConviteSlugRoute: ConviteSlugRoute,
  PainelConviteTokenRoute: PainelConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
